# Accounts Service Justfile
# https://just.systems/man/en/

# List available commands
default:
    @just --list

# Build the accounts service
build:
    go build -o server

# Run the accounts service
run:
	air

# Run without building (development mode)
run-prod: build
	./server

# Run tests for all packages
test:
    go test ./...

# Run tests with verbose output
test-v:
    go test -v ./...

# Generate code from proto files using goctl
proto:
    goctl rpc protoc --zrpc_out . --go-grpc_out . --go_out=. accounts.proto

# Run with delve debugger
debug:
    dlv debug accounts.go

# Debug with specific arguments
debug-args *args:
    dlv debug accounts.go -- {{args}}

# Format Go code
fmt:
    go fmt ./...

# Lint Go code
lint:
    go vet ./...

# Clean build artifacts
clean:
    rm -f accounts

# Show current Go version
go-version:
    go version
