// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: access.proto

package accessclient

import (
	"context"

	"github.com/tempest-org/tempest/access/access"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = access.Request
	Response = access.Response

	Access interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultAccess struct {
		cli zrpc.Client
	}
)

func NewAccess(cli zrpc.Client) Access {
	return &defaultAccess{
		cli: cli,
	}
}

func (m *defaultAccess) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := access.NewAccessClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
