// Code generated by goctl. DO NOT EDIT.
// Source: access.proto

package server

import (
	"context"

	"github.com/tempest-org/tempest/access/access"
	"github.com/tempest-org/tempest/access/internal/logic"
	"github.com/tempest-org/tempest/access/internal/svc"
)

type AccessServer struct {
	svcCtx *svc.ServiceContext
	access.UnimplementedAccessServer
}

func NewAccessServer(svcCtx *svc.ServiceContext) *AccessServer {
	return &AccessServer{
		svcCtx: svcCtx,
	}
}

func (s *AccessServer) Check(ctx context.Context, in *access.CheckAccessRequest) (*access.CheckAccessResponse, error) {
	l := logic.NewCheckLogic(ctx, s.svcCtx)
	return l.Check(in)
}

func (s *AccessServer) Grant(ctx context.Context, in *access.GrantAccessRequest) (*access.Empty, error) {
	l := logic.NewGrantLogic(ctx, s.svcCtx)
	return l.Grant(in)
}

func (s *AccessServer) Revoke(ctx context.Context, in *access.RevokeAccessRequest) (*access.Empty, error) {
	l := logic.NewRevokeLogic(ctx, s.svcCtx)
	return l.Revoke(in)
}

func (s *AccessServer) GetSubjectAccess(ctx context.Context, in *access.GetSubjectAccessRequest) (*access.GetSubjectAccessResponse, error) {
	l := logic.NewGetSubjectAccessLogic(ctx, s.svcCtx)
	return l.GetSubjectAccess(in)
}

func (s *AccessServer) GetObjectSubjects(ctx context.Context, in *access.GetObjectSubjectsRequest) (*access.GetObjectSubjectsResponse, error) {
	l := logic.NewGetObjectSubjectsLogic(ctx, s.svcCtx)
	return l.GetObjectSubjects(in)
}

func (s *AccessServer) HealthCheck(ctx context.Context, in *access.HealthCheckRequest) (*access.HealthCheckResponse, error) {
	l := logic.NewHealthCheckLogic(ctx, s.svcCtx)
	return l.HealthCheck(in)
}
