// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: access.proto

package server

import (
	"context"

	"github.com/tempest-org/tempest/access/access"
	"github.com/tempest-org/tempest/access/internal/logic"
	"github.com/tempest-org/tempest/access/internal/svc"
)

type AccessServer struct {
	svcCtx *svc.ServiceContext
	access.UnimplementedAccessServer
}

func NewAccessServer(svcCtx *svc.ServiceContext) *AccessServer {
	return &AccessServer{
		svcCtx: svcCtx,
	}
}

func (s *AccessServer) Ping(ctx context.Context, in *access.Request) (*access.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
